FROM gradle:8.5-jdk17 AS builder
WORKDIR /app

COPY . .

RUN chmod +x ./gradlew
RUN ./gradlew clean :api:bootJar -x test --no-daemon
RUN rm -rf /root/.gradle

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

COPY --from=builder /app/api/build/libs/api*.jar /app/api.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "/app/api.jar"]
