FROM gradle:8.5-jdk17 AS builder
WORKDIR /app

COPY . .

RUN chmod +x ./gradlew
RUN ./gradlew clean :batch:bootJar -x test --no-daemon
RUN rm -rf /root/.gradle

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

COPY --from=builder /app/batch/build/libs/batch*.jar /app/batch.jar

EXPOSE 8083

ENTRYPOINT ["java", "-jar", "/app/batch.jar"]
