FROM gradle:8.5-jdk17 AS builder
WORKDIR /app

COPY . .

RUN chmod +x ./gradlew
RUN ./gradlew clean :corp:bootJar -x test --no-daemon
RUN rm -rf /root/.gradle

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

COPY --from=builder /app/corp/build/libs/corp*.jar /app/corp.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "/app/corp.jar"]
